openapi: 3.0.3

info:
  title: Bilberry v3 API
  description: The public and internal API of Bilberry v3
  version: 0.0.0

servers:
  - url: 'https://bilberry.test/api/v0'

#security:
#  - BasicAuth: []

paths:
  /products:
    $ref: './api/products/Products.yaml'
  /product/{product}:
    $ref: './api/products/Product.yaml'
  /availabilities:
    $ref: './api/availability/Availabilities.yaml'
  /availabilities/{availability}:
    $ref: './api/availability/Availability.yaml'
  /bookings:
    $ref: './api/bookings/Bookings.yaml'
  /bookings/{booking}:
    $ref: './api/bookings/Booking.yaml'
  /invoices/{invoice}:
    $ref: './api/reporting/Invoice.yaml'
  /notifications:
    $ref: './api/notifications/Notifications.yaml'

  /users: {}
  /resources: {}
  /vat-models: {}
  /reports: {}
  /staff: {}
