openapi: 3.0.3
info:
  title: Bilberry v3 API
  description: The public and internal API of Bilberry v3
  version: 0.0.0
servers:
  - url: 'https://bilberry.test/api/v0'
#security:
#  - BasicAuth: []
paths:

  /bookings:
    get:
      description: Returns list of bookings
      tags:
        - Booking API
      parameters:
        - name: name
          in: query
          description: Filters by name (ignores capitalisation, matches if provided name is part of full name)
          schema:
            type: string
        - name: email
          in: query
          description: Filters by email
          schema:
            type: string
            format: email
        - name: phone
          in: query
          description: Filters by phone number (whitespace is trimmed, can omit country code)
          schema:
            $ref: '#/components/schemas/PhoneNumber'
      responses:
        200:
          description: Successfully retrieved bookings from the server
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Booking'
                  links:
                    $ref: '#/components/schemas/PaginationLinks'
    post:
      description: Creates new booking
      tags:
        - Booking API
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Booking'
      responses:
        201:
          description: Successfully created new booking on the server
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Booking'

  /bookings/{booking}:
    get:
      description: Returns a single booking based on its ID
      tags:
        - Booking API
      parameters:
        - $ref: '#/components/parameters/BookingId'
      responses:
        200:
          description: Successfully retrieved the booking from the server
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Booking'
        404:
          $ref: '#/components/responses/404NotFound'
    patch:
      description: Patch a specific booking based on its ID. This is inspired by the JSON patch syntax with some modifications such as custom operations and modified array referencing
      tags:
        - Booking API
      parameters:
        - $ref: '#/components/parameters/BookingId'
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                oneOf:
                  - $ref: '#/components/schemas/JSONPatch'
                  - type: object
                    properties:
                      op:
                        type: string
                        description: Custom JSON Patch operations for this endpoint
                        enum: [create-invoice, cancel-invoice, create-online-payment]
      responses:
        200:
          description: Successfully updated the booking on the server
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Booking'
    delete:
      description: Cancel a specific booking based on its ID
      tags:
        - Booking API
      parameters:
        - $ref: '#/components/parameters/BookingId'
      responses:
        200:
          description: Successfully cancelled the booking on the server

  /invoices/{invoice}:
    get:
      description: Returns a single invoice based on its reference
      parameters:
        - $ref: '#/components/parameters/InvoiceRef'
      tags:
        - Reporting API
      responses:
        200:
          description: Successfully retrieved the invoice from the server
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DetailedInvoice'
        404:
          $ref: '#/components/responses/404NotFound'

#  /products:
#    get:
#      description: Returns a list of products
#      responses:
#        200:
#          description: Successfully retrieved the products from the server
#          content:
#            application/json:
#              schema:
#                type: object
#                properties:
#                  data:
#                    type: array
#                    items:
#                      $ref: '#/components/schemas/Product'
#    post:
#      description: Inserts single product and all its nested relations
#      requestBody:
#        required: true
#        content:
#          application/json:
#            schema:
#              $ref: '#/components/schemas/Product'
#      responses:
#        201:
#          description: Successfully created a new product on the server
#          content:
#            application/json:
#              schema:
#                $ref: '#/components/schemas/Product'
#
#  /products/{product}:
#    get:
#      description: Returns a single product based on its ID
#      parameters:
#        - $ref: '#/components/parameters/ProductId'
#      responses:
#        200:
#          description: Successfully retrieved the product from the server
#          content:
#            application/json:
#              schema:
#                type: object
#                properties:
#                  data:
#                    $ref: '#/components/schemas/Product'
#        404:
#          $ref: '#/components/responses/404NotFound'

  /users: {}
  /instances: {}
  /resources: {}
  /vat-models: {}
  /reports: {}
  /notifications: {}
  /staff: {}
components:
  parameters:
    ProductId:
      name: product
      in: path
      required: true
      description: The product ID
      schema:
        type: integer
        minimum: 0
    BookingId:
      name: booking
      in: path
      required: true
      description: The booking ID
      schema:
        type: string
        format: uuid
    InvoiceRef:
      name: invoice
      in: path
      required: true
      description: The invoice ref
      schema:
        type: integer
        minimum: 0
      example: "100427"
  responses:
    404NotFound:
      description: Not found error
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
              details:
                type: object
                properties: {}
              code:
                type: integer # or string if allowing for codes like: PROD-1000
#    401Unauthorized:
#    403Forbidden:
#    500ServerError:
  schemas:
#    Product:
#      type: object
#      required:
#        - name
#        - description
#      properties:
#        id:
#          type: integer
#          readOnly: true
#        name:
#          type: string
#        description:
#          type: string
#        web:
#          $ref: '#/components/schemas/WidgetInfo'
#        cutoff:
#          type: integer
#        accessStatus:
#          $ref: '#/components/schemas/ProductAccessStatus'
#        ticketOptions:
#          type: array
#          items:
#            $ref: '#/components/schemas/TicketOption'
#        termsAndConditions: {}
#        staffRequirements:
#          type: array
#          items:
#            $ref: '#/components/schemas/StaffRequirement'
#        location:
#          $ref: '#/components/schemas/Location'
#    WidgetInfo:
#      type: object
#      properties: {}
#    TicketOption:
#      type: object
#      properties: {}
#    StaffRequirement:
#      type: object
#      properties: {}
#    Location:
#      type: object
#      properties: {}
#    ProductAccessStatus:
#      type: string
#      enum: [public, private, api-only]

    Booking:
      allOf:
        - type: object
          required: [id]
          properties:
            id:
              $ref: '#/components/schemas/ULID'
        - $ref: '#/components/schemas/BookingMetaInfo'
        - type: object
          required: [expiresAt, tickets, invoice, creditedInvoices, depositInvoices, payments, onlinePayments]
          properties:
            expiresAt:
              type: string
              format: date-time
              nullable: true
              readOnly: true
            tickets:
              type: array
              items:
                $ref: '#/components/schemas/QuantifiedBookable'
            invoice:
              allOf:
                - $ref: '#/components/schemas/Invoice'
                - readOnly: true
                  nullable: true
            creditedInvoices:
              type: array
              readOnly: true
              items:
                allOf:
                  - $ref: '#/components/schemas/Invoice'
                  - type: object
                    required: [creditedAt]
                    properties:
                      creditedAt:
                        type: string
                        format: date-time
            depositInvoices:
              type: array
              items:
                $ref: '#/components/schemas/DepositInvoice'
            payments:
              type: array
              items:
                $ref: '#/components/schemas/Payment'
            onlinePayments:
              type: array
              readOnly: true
              items:
                $ref: '#/components/schemas/OnlinePayment'
    BookingMetaInfo:
      type: object
      required: [firstName, lastName, email, phone]
      properties:
        firstName:
          type: string
          nullable: true
        lastName:
          type: string
          nullable: true
        email:
          type: string
          format: email
          nullable: true
        phone:
          allOf:
            - $ref: '#/components/schemas/PhoneNumber'
            - nullable: true
    QuantifiedBookable:
      type: object
      required: [id, bookableId, quantity]
      properties:
        id:
          $ref: '#/components/schemas/ULID'
        bookableId:
          type: integer
        quantity:
          type: integer
          minimum: 1
          default: 1
            # TODO: more info about product, ticket option etc. (separate schema!)
    Payment:
      type: object
      required: [id, currency, amountMinor, createdAt, type]
      properties:
        id:
          $ref: '#/components/schemas/ULID'
        currency:
          $ref: '#/components/schemas/Currency'
        amountMinor:
          type: integer
        createdAt:
          type: string
          format: date-time
          readOnly: true
        type:
          type: string
          enum: [online, checkout, ...]
    OnlinePayment:
      type: object
      required: [id, provider, currency, amountMinor, createdAt, status, statusAt, bilberryPaymentId]
      readOnly: true
      properties:
        id:
          type: string
          format: uuid
        provider:
          type: string
          enum: [nets, stripe]
        currency:
          $ref: '#/components/schemas/Currency'
        amountMinor:
          type: integer
        createdAt:
          type: string
          format: date-time
        status:
          type: string
          enum: [created, timed-out, completed, cancelled]
        statusAt:
          type: string
          format: date-time
        bilberryPaymentId:
          allOf:
            - $ref: '#/components/schemas/ULID'
            - nullable: true
    Invoice:
      type: object
      required: [id, createdAt]
      nullable: true
      properties:
        id:
          type: integer
          readOnly: true
        createdAt:
          type: string
          format: date-time
          readOnly: true
    DepositInvoice:
      allOf:
        - $ref: '#/components/schemas/Invoice'
        - type: object
          required: [amountMinor, currency, creditedAt]
          properties:
            amountMinor:
              type: integer
            currency:
              $ref: '#/components/schemas/Currency'
            creditedAt:
              type: string
              format: date-time
              readOnly: true
              nullable: true
    DetailedInvoice:
      readOnly: true
      allOf:
        - $ref: '#/components/schemas/Invoice'
        - $ref: '#/components/schemas/BookingMetaInfo'
        - type: object
          required: [currency, totalAmountGross, totalAmountNet, totalAmountVAT, items, creditedAt]
          properties:
            currency:
              $ref: '#/components/schemas/Currency'
            # TODO: amount minor | string vs integer vs float
            totalAmountGross:
              type: integer
            totalAmountNet:
              type: integer
            totalAmountVAT:
              type: integer
            items:
              type: array
              items:
                type: object
                properties:
                  name:
                    type: string
                  amountNet:
                    type: integer
                  amountGross:
                    type: integer
                  amountVAT:
                    type: integer
                  quantity:
                    type: integer
            creditedAt:
              type: string
              format: date-time
              nullable: true
    JSONPatch:
      oneOf:
        - type: object
          required: [op, path, value]
          properties:
            op:
              allOf:
                - $ref: '#/components/schemas/JSONPatchOp'
                - enum: [add, replace, test]
            path:
              $ref: '#/components/schemas/JSONPatchPath'
            value:
              $ref: '#/components/schemas/JSONPatchValue'
        - type: object
          required: [op, path]
          properties:
            op:
              allOf:
                - $ref: '#/components/schemas/JSONPatchOp'
                - enum: [remove]
            path:
              $ref: '#/components/schemas/JSONPatchPath'
#        - type: object
#          required: [op, from, path]
#          properties:
#            op:
#              type: string
#              enum: [move, copy]
#            from:
#              $ref: '#/components/schemas/JSONPatchPath'
#            path:
#              $ref: '#/components/schemas/JSONPatchPath'
    JSONPatchOp:
      type: string
      description: The operation to be carried out
    JSONPatchPath:
      type: string
      description: A path in the request object of the related POST request following modified JSON patch syntax
      example: /my/path/12/asd
    JSONPatchValue:
      description: The value used for the operation (any type)

    PaginationLinks:
      type: object
      required: [next, prev]
      properties:
        next:
          type: string
          format: url
          nullable: true
        prev:
          type: string
          format: url
          nullable: true

    PhoneNumber:
      type: string
      format: phone
      example: '+4712345678'
    Currency:
      type: string
      format: currency
      minLength: 3
      maxLength: 3
      example: NOK
    ULID:
      type: string
      format: ulid
      example: 01F8MECHZX3TBDSZ7XR8H8JHAF
      pattern: ^[0-7][0-9A-HJKMNP-TV-Z]{25}$
      readOnly: true