get:
  description: Returns list of products
  tags: [ Products API ]
  parameters:
    - $ref: '../../parameters/query/PageCursor.yaml'
    - $ref: '../../parameters/query/PerPage.yaml'
  responses:
    200:
      description: Successfully retrieved products from the server
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: '../../schemas/products/Product.yaml'
              links:
                $ref: '../../schemas/pagination/Links.yaml'
post:
  description: Creates new product
  tags: [ Products API ]
  requestBody:
    content:
      application/json:
        schema:
          $ref: '../../schemas/products/Product.yaml'
  responses:
    201:
      description: Successfully created new product on the server
      content:
        application/json:
          schema:
            $ref: '../../schemas/products/ProductWrapped.yaml'