type: object
required:
  - name
  - description
properties:
  id:
    type: integer
    readOnly: true
  name:
    type: string
  description:
    type: string
  web:
    $ref: './WidgetInfo.yaml'
  cutoff:
    type: integer
  accessStatus:
    $ref: './AccessStatus.yaml'
  ticketOptions:
    type: array
    items:
      $ref: './TicketOption.yaml'
  termsAndConditions: {}
  staffRequirements:
    type: array
    items:
      $ref: './StaffRequirement.yaml'
  location:
    $ref: './Location.yaml'