type: object
properties:
  id:
    $ref: '../types/ID.yaml'
  createdAt:
    $ref: '../types/CreatedAt.yaml'
  name:
    type: string
  description:
    type: string
  type:
    $ref: './ProductType.yaml'
  widgetInfo:
    $ref: './WidgetInfo.yaml'
  cutoffTime:
    type: integer
  status:
    $ref: './ProductStatus.yaml'
  ticketOptions:
    type: array
    items:
      $ref: './TicketOption.yaml'
  cancellationPolicy:
    $ref: './CancellationPolicyShort.yaml'
  tags:
    type: array
    items:
      $ref: '../types/Tag.yaml'
#  staffRequirements:
#    type: array
#    items:
#      $ref: './StaffRequirement.yaml'
  location:
    $ref: './Location.yaml'
  discountPolicies: {}