openapi: 3.0.3

info:
  title: Bilberry v3 oauth API
  description: The oauth endpoints of the bilberry API
  version: 0.0.0

servers:
  - url: 'https://bilberry.test/oauth'

#security:
#  - BasicAuth: []

paths: {}