openapi: 3.0.3

info:
  title: Bilberry v3 API
  description: The public and internal API of Bilberry v3
  version: 0.0.0

servers:
  - url: 'https://bilberry.app'
  - url: 'https://www.bilberry.app'

components:
  securitySchemes:
    elderberryOAuth:
      $ref: ./security/elderberryOAuth.yaml

security:
  - elderberryOAuth:
    - admin

paths:
  # Products API
  /{tenant}/v0/products:
    $ref: ./endpoints/products/ProductsEndpoints.yaml
  /{tenant}/v0/products/{product}:
    $ref: ./endpoints/products/ProductEndpoints.yaml
  /{tenant}/v0/products/{product}/bookables:
    $ref: ./endpoints/products/BookablesEndpoints.yaml
  /{tenant}/v0/products/{product}/availability:
    $ref: ./endpoints/products/AvailabilityEndpoints.yaml

  # VAT API
  /{tenant}/v0/vat-models:
    $ref: ./endpoints/vat/VatsEndpoints.yaml
  /{tenant}/v0/vat-models/{vat-model}:
    $ref: ./endpoints/vat/VatEndpoints.yaml

  # Bookings API
  /{tenant}/v0/bookings:
    $ref: ./endpoints/bookings/BookingsEndpoints.yaml
  /{tenant}/v0/bookings/{booking}:
    $ref: ./endpoints/bookings/BookingEndpoints.yaml

  # Reporting API
  /{tenant}/v0/invoices/{invoice}:
    $ref: ./endpoints/reporting/InvoiceEndpoints.yaml

#  /notifications:

#    $ref: ./endpoints/notifications/NotificationsEndpoints.yaml

  /{tenant}/v0/users: {}
  /{tenant}/v0/resources: {}

  /{tenant}/v0/reports: {}
  /{tenant}/v0/staff: {}
