openapi: 3.0.3

info:
  title: Bilberry v3 API
  description: The public and internal API of Bilberry v3
  version: 0.0.0

servers:
  - url: 'https://bilberry.app'

components:
  securitySchemes:
    elderberryOAuth:
      $ref: './security/elderberryOAuth.yaml'

security:
  - elderberryOAuth:
    - admin

#security:
#  - BasicAuth: []

paths:
  # Products API
  /v0/{tenant}/products:
    $ref: './endpoints/products/ProductsEndpoints.yaml'
  /v0/{tenant}/products/{product}:
    $ref: './endpoints/products/ProductEndpoints.yaml'
  /v0/{tenant}/products/{product}/bookables:
    $ref: './endpoints/products/BookablesEndpoints.yaml'
  /v0/{tenant}/products/{product}/availability:
    $ref: './endpoints/products/AvailabilityEndpoints.yaml'

  # VAT API
  /v0/{tenant}/vat-models:
    $ref: './endpoints/vat/VatsEndpoints.yaml'
  /v0/{tenant}/vat-models/{vat-model}:
    $ref: './endpoints/vat/VatEndpoints.yaml'

  # Bookings API
  /v0/{tenant}/bookings:
    $ref: './endpoints/bookings/BookingsEndpoints.yaml'
  /v0/{tenant}/bookings/{booking}:
    $ref: './endpoints/bookings/BookingEndpoints.yaml'

  # Reporting API
  /v0/{tenant}/invoices/{invoice}:
    $ref: './endpoints/reporting/InvoiceEndpoints.yaml'

#  /notifications:

#    $ref: './endpoints/notifications/NotificationsEndpoints.yaml'

  /v0/{tenant}/users: {}
  /v0/{tenant}/resources: {}

  /v0/{tenant}/reports: {}
  /v0/{tenant}/staff: {}
