type: object
required: [name, description, status]
properties:
  name:
    type: string
  description:
    type: string
  status:
    $ref: ./ProductStatus.yaml
  cutoffTime:
    type: integer
    default: 0
  ticketOptions:
    type: array
    nullable: true # null, undefined get treated like []
    items:
      $ref: ./TicketOption.yaml
  widgetInfo:
    $ref: ./WidgetInfo.yaml
  location:
    $ref: ./Location.yaml